# Generated by Django 5.1.6 on 2025-02-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_group_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
